Developer tools
epiverse-trace/serofoi pull request #134
Opened 2023-11-21 15:13 UTC by ntorresd

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

This PR updates the package template files:
- .github/workflows/pkgdown.yaml
- tests/spelling.R
- tests/testthat/helper-state.R
- tests/testthat/setup-options.R
- tools/check.env

In accordance to the discussion in [November 2023 spring cleaning #101](https://github.com/epiverse-trace/packagetemplate/issues/101)

2023-11-21 15:36 UTC, Bisaloo approved these changes

2023-11-21 15:36 UTC, Bisaloo requested changes
Could you also update the other GitHub Actions workflows please?

2023-11-21 17:51 UTC, jpavlich commented
> > Could you also update the other GitHub Actions workflows please?
> 
> Done. Please let me know whether we should keep line 47 in `test-coverage.yaml`. @jpavlich , do you remember why we added this to the workflow?

That was to be able to use development versions of rstan. Since we are sticking only to CRAN versions, I guess we don't need it anymore

2023-12-15 14:30 UTC, Bisaloo commented on tools/check.env
> +_R_CHECK_CRAN_INCOMING_NOTE_GNU_MAKE_=false
```suggestion
_R_CHECK_CRAN_INCOMING_NOTE_GNU_MAKE_=true
```

My understanding of the code here seems to suggest it should be `true`. That's somewhat counter intuitive but can we give it a try please?

https://github.com/wch/r-source/blob/b12ffba7584825d6b11bba8b7dbad084a74c1c20/src/library/tools/R/check.R#L2960C2-L2960C2

2023-12-15 19:06 UTC, Bisaloo commented
Clean diff is here: https://github.com/epiverse-trace/serofoi/compare/developer-tools2?expand=1. Can I force push it here?

2023-12-16 09:02 UTC, merged

2023-12-19 17:40 UTC, ntorresd commented
Closes #86 and #101